export default [
  {
    id: 1,
    num: "001",
    name: "Bulbasaur",
    img: "http://www.serebii.net/pokemongo/pokemon/001.png",
    type: ["Grass", "Poison"],
  },
  {
    id: 2,
    num: "002",
    name: "Ivysaur",
    img: "http://www.serebii.net/pokemongo/pokemon/002.png",
    type: ["Grass", "Poison"],
  },
  {
    id: 3,
    num: "003",
    name: "Venusaur",
    img: "http://www.serebii.net/pokemongo/pokemon/003.png",
    type: ["Grass", "Poison"],
  },
  {
    id: 4,
    num: "004",
    name: "Charmander",
    img: "http://www.serebii.net/pokemongo/pokemon/004.png",
    type: ["Fire"],
  },
  {
    id: 5,
    num: "005",
    name: "Charmeleon",
    img: "http://www.serebii.net/pokemongo/pokemon/005.png",
    type: ["Fire"],
  },
  {
    id: 6,
    num: "006",
    name: "Charizard",
    img: "http://www.serebii.net/pokemongo/pokemon/006.png",
    type: ["Fire", "Flying"],
  },
  {
    id: 7,
    num: "007",
    name: "Squirtle",
    img: "http://www.serebii.net/pokemongo/pokemon/007.png",
    type: ["Water"],
  },
  {
    id: 8,
    num: "008",
    name: "Wartortle",
    img: "http://www.serebii.net/pokemongo/pokemon/008.png",
    type: ["Water"],
  },
  {
    id: 9,
    num: "009",
    name: "Blastoise",
    img: "http://www.serebii.net/pokemongo/pokemon/009.png",
    type: ["Water"],
  },
  {
    id: 10,
    num: "010",
    name: "Caterpie",
    img: "http://www.serebii.net/pokemongo/pokemon/010.png",
    type: ["Bug"],
  },
  {
    id: 11,
    num: "011",
    name: "Metapod",
    img: "http://www.serebii.net/pokemongo/pokemon/011.png",
    type: ["Bug"],
  },
  {
    id: 12,
    num: "012",
    name: "Butterfree",
    img: "http://www.serebii.net/pokemongo/pokemon/012.png",
    type: ["Bug", "Flying"],
  },
];
